from app.chain.runnable import Runnable
from transformers import pipeline
from app.schemas import (
    PromptInput,
    PromptOutput,
    LLMOutput,
    ParsedAnswer,
)
# pipeline configer with LLm
generator = pipeline(
    "text-generation",
    model="HuggingFaceTB/SmolLM2-135M-Instruct"
)
# The PromptBuilder class is a specific implementation of the Runnable interface that takes a PromptInput and produces a PromptOutput. The invoke method constructs a prompt string based on the provided dataset statistics and user question, following a specific format that instructs the AI to use only the provided data to answer the question. If the answer cannot be determined from the data, it instructs the AI to respond with "Not enough information." The generated prompt is then returned as a PromptOutput object.
class PromptBuilder(Runnable[PromptInput, PromptOutput]):


    def invoke(self, data: PromptInput) -> PromptOutput:


        prompt = f"""
You are a strict data analyst AI.

Use ONLY the provided dataset statistics.

If the answer cannot be determined from the data,
say: "Not enough information."

Dataset statistics:
{data.stats}

User question:
{data.question}

Answer briefly and clearly.
"""
# The generated prompt is returned as a PromptOutput object, which can be used in subsequent steps of the processing chain, such as sending it to a language model for generating an answer.
        return PromptOutput(prompt=prompt)
    

# The LLMRunner class is another implementation of the Runnable interface that takes a PromptOutput and produces an LLMOutput. The invoke method uses the previously defined text generation pipeline to generate a response based on the prompt contained in the PromptOutput. The generated text is extracted from the result and returned as an LLMOutput object.
class LLMRunner(Runnable[PromptOutput, LLMOutput]):

    def invoke(self, data: PromptOutput) -> LLMOutput:

        result = generator(
            data.prompt,
            max_new_tokens=250,
            truncation=True
        )

        text = result[0]["generated_text"]

        return LLMOutput(raw_text=text)
    
# The ResponseParser class is a simple implementation of the Runnable interface that takes an LLMOutput and produces a ParsedAnswer. The invoke method processes the raw text output from the language model, stripping any leading or trailing whitespace, and returns the cleaned answer as a ParsedAnswer object. This step is crucial for extracting a clean and structured answer from the potentially verbose output generated by the language model.
class ResponseParser(Runnable[LLMOutput, ParsedAnswer]):

    def invoke(self, data: LLMOutput) -> ParsedAnswer:

        cleaned = data.raw_text.strip()

        return ParsedAnswer(answer=cleaned)    